# Generated by Django 3.0.3 on 2021-09-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgitbranch',
            name='merge_status',
            field=models.BooleanField(default=False),
        ),
    ]
