# Generated by Django 3.0.3 on 2021-09-05 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dgit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DGitRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dgit_dgitrepository_created', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dgit_dgitrepository_created', to='access_control.Policy')),
            ],
        ),
    ]
