# Generated by Django 3.0.3 on 2021-09-05 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dgit', '0002_dgitrepository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgitrepository',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
