# Generated by Django 3.0.3 on 2021-09-09 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('access_control', '0001_initial'),
        ('dgit', '0003_dgitbranch_is_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoFileTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.UUIDField(editable=False, unique=True, verbose_name='Public identifier')),
                ('path', models.TextField()),
                ('name', models.TextField()),
                ('identifier', models.UUIDField(editable=False, unique=True, verbose_name='Public identifier')),
            ],
        ),
        migrations.AlterField(
            model_name='dgitblob',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgit_dgitblob_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dgitbranch',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgit_dgitbranch_repository', to='dgit.DGitRepository'),
        ),
        migrations.AlterField(
            model_name='dgitrepository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgit_dgitrepository_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dgitrepository',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dgit_dgitrepository_policy', to='access_control.Policy'),
        ),
        migrations.CreateModel(
            name='DGitRepositoryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('name', models.CharField(max_length=100)),
                ('path', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgit_dgitrepositoryfile_owner', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgit_dgitrepositoryfile_repository', to='dgit.DGitRepository')),
            ],
        ),
    ]
