# Generated by Django 3.0.3 on 2021-09-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgit', '0004_auto_20210909_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repofiletracker',
            name='identifier',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='repofiletracker',
            name='session',
            field=models.UUIDField(editable=False),
        ),
    ]
