# Generated by Django 3.0.3 on 2021-09-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgit', '0005_auto_20210925_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgitbranch',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldgitbranch',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
