# Generated by Django 3.0.3 on 2021-09-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userssh',
            name='key',
            field=models.TextField(),
        ),
    ]
