# Generated by Django 3.0.3 on 2021-09-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorypermission',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repositorypermission',
            name='is_merge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repositorypermission',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repositorypermission',
            name='is_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='permissions',
            field=models.ManyToManyField(to='access_control.RepositoryPermission'),
        ),
    ]
