# Generated by Django 3.0.3 on 2021-09-25 06:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dgit', '0002_historicaldgitbranch_historicaldgitrepository'),
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloneToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_control_clonetoken_repository', to='dgit.DGitRepository')),
            ],
        ),
    ]
