# Generated by Django 3.0.3 on 2021-09-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_repositoryinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryinvite',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
