# Generated by Django 3.0.3 on 2021-09-16 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DGitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Commit'), (2, 'Push'), (3, 'Branch'), (4, 'Access'), (5, 'Repository'), (6, 'Settings')])),
                ('data', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_dgitlog_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
